application:
  kafka:
    topic-name: demo-topic

spring:
  kafka:
    client-id: demo-consumer
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093
    listener:
      ack-mode: record
    producer:
      client-id: dlt-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
      retries: 3
    consumer:
      max-poll-records: 3
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

    # https://docs.spring.io/spring-kafka/api/constant-values.html
    properties:
      spring.json.value.default.type: edu.sandbox.springbootkafka.consumer.model.Message
      spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.type.mapping: edu.sandbox.springbootkafka.producer.model.Message:edu.sandbox.springbootkafka.consumer.model.Message
